# Generated by Django 5.1.4 on 2025-09-04 04:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='No', max_length=250)),
                ('street_address1', models.CharField(default='No', max_length=250)),
                ('street_address2', models.CharField(default='No', max_length=250)),
                ('city', models.CharField(default='No', max_length=150)),
                ('State_Region', models.CharField(default='No', max_length=250)),
                ('ZIP_code', models.IntegerField(default=0)),
                ('country', models.CharField(default='No', max_length=250)),
                ('phone_number', models.IntegerField(default=0)),
                ('phone_code', models.IntegerField(default=0)),
                ('additional_comment', models.CharField(default='No', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(default='No', max_length=250)),
                ('product_description', models.CharField(default='No', max_length=250)),
                ('Product_Category', models.CharField(default='No', max_length=250)),
                ('Product_price_old', models.CharField(default='No', max_length=250)),
                ('Product_price_new', models.CharField(default='No', max_length=250)),
                ('Product_rating', models.IntegerField(default=0)),
                ('Product_color1', models.CharField(default='No', max_length=250)),
                ('Product_color2', models.CharField(default='No', max_length=250)),
                ('Product_color3', models.CharField(default='No', max_length=250)),
                ('Product_color4', models.CharField(default='No', max_length=250)),
                ('Product_color5', models.CharField(default='No', max_length=250)),
                ('Product_color6', models.CharField(default='No', max_length=250)),
                ('Product_color7', models.CharField(default='No', max_length=250)),
                ('Product_color8', models.CharField(default='No', max_length=250)),
                ('Product_color9', models.CharField(default='No', max_length=250)),
                ('Product_color10', models.CharField(default='No', max_length=250)),
                ('Product_XS', models.IntegerField(default=0)),
                ('Product_S', models.IntegerField(default=0)),
                ('Product_M', models.IntegerField(default=0)),
                ('Product_L', models.IntegerField(default=0)),
                ('Product_XL', models.IntegerField(default=0)),
                ('Product_2Xl', models.IntegerField(default=0)),
                ('Product_3Xl', models.IntegerField(default=0)),
                ('Product_4Xl', models.IntegerField(default=0)),
                ('Product_5Xl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfavorites', to=settings.AUTH_USER_MODEL)),
                ('favorited', models.ManyToManyField(related_name='userfavorited', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(default='No', max_length=250)),
                ('Color', models.CharField(default='No', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercart', to=settings.AUTH_USER_MODEL)),
                ('Item', models.ManyToManyField(related_name='cartitem', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='No', max_length=150)),
                ('middle_name', models.CharField(default='No', max_length=150)),
                ('last_name', models.CharField(default='No', max_length=150)),
                ('id_number', models.IntegerField(default=0)),
                ('email_address', models.EmailField(default='No', max_length=254)),
                ('phone_number', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
