# Generated by Django 5.1.4 on 2025-09-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_product_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorname', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color10', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color3', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color4', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color5', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color6', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color7', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color8', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_color9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color9', to='app.color'),
        ),
    ]
