# Generated by Django 5.1.4 on 2025-09-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_favoriteitem_delete_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Category_en',
            field=models.CharField(default='No', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Category_ka',
            field=models.CharField(default='No', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_name_en',
            field=models.CharField(default='No', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_name_ka',
            field=models.CharField(default='No', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_en',
            field=models.CharField(default='No', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_ka',
            field=models.CharField(default='No', max_length=250, null=True),
        ),
    ]
