# Generated by Django 5.1.4 on 2025-09-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_product_category_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
