# Generated by Django 5.1.4 on 2025-09-07 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cartitem_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(default='0', max_length=250)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderaddress', to='app.address_info')),
                ('items', models.ManyToManyField(related_name='orderitems', to='app.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
