# Generated by Django 5.1.4 on 2025-09-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_address_info_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address_Info',
        ),
    ]
