# Generated by Django 5.1.4 on 2025-09-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_product_product_is_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
