# Generated by Django 5.1.4 on 2025-09-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cartitem_item_cart_cartitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_image1',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image10',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image2',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image3',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image4',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image5',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image6',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image7',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image8',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image9',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
