# Generated by Django 5.1.4 on 2025-09-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_product_image1_product_product_image10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image1',
            field=models.ImageField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image10',
            field=models.ImageField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image2',
            field=models.ImageField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image3',
            field=models.ImageField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image4',
            field=models.ImageField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image5',
            field=models.ImageField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image6',
            field=models.ImageField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image7',
            field=models.ImageField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image8',
            field=models.ImageField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image9',
            field=models.ImageField(default='/', upload_to=''),
        ),
    ]
