# Generated by Django 5.1.4 on 2025-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_product_color1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_color1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_color10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_color2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_color3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_color4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_color5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_color6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_color7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_color8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_color9',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_color',
            field=models.ManyToManyField(default='', related_name='color10', to='app.color'),
        ),
    ]
