# Generated by Django 5.1.4 on 2025-09-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_product_color1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
