# Generated by Django 5.1.4 on 2025-09-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_product_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Category_ka',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_name_ka',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_ka',
        ),
    ]
