# Generated by Django 5.1.4 on 2025-09-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_address_info_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address_info',
            name='user',
        ),
    ]
