# Generated by Django 5.1.4 on 2025-09-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_order_address_delete_address_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='No', max_length=250)),
                ('street_address1', models.CharField(default='No', max_length=250)),
                ('street_address2', models.CharField(default='No', max_length=250)),
                ('city', models.CharField(default='No', max_length=150)),
                ('State_Region', models.CharField(default='No', max_length=250)),
                ('ZIP_code', models.IntegerField(default=0)),
                ('country', models.CharField(default='No', max_length=250)),
                ('phone_number', models.IntegerField(default=0)),
                ('phone_code', models.IntegerField(default=0)),
                ('additional_comment', models.CharField(default='No', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderaddress', to='app.address_info'),
        ),
    ]
