# Generated by Django 5.1.4 on 2025-09-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_category_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category'),
        ),
    ]
