# Generated by Django 5.1.4 on 2025-09-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_is_male',
            field=models.BooleanField(default=False),
        ),
    ]
