# Generated by Django 5.1.4 on 2025-09-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Active',
        ),
    ]
